apiVersion: v2
name: mautrix-whatsapp
version: 0.1.1
description: Chart for Matrix Whatsapp Bridge
keywords:
  - matrix
  - mautrix-whatsapp
  - bridge
  - whatsapp
sources:
  - https://github.com/mautrix/whatsapp
maintainers:
  - name: alexlebens
icon: https://avatars.githubusercontent.com/u/88519669?s=48&v=4
appVersion: v0.10.7
