apiVersion: v2
name: freshrss
version: 0.0.3
description: Chart for Freshrss
keywords:
  - rss
sources:
  - https://github.com/FreshRSS/FreshRSS
maintainers:
  - name: alexlebens
icon: https://avatars.githubusercontent.com/u/9414285?s=48&v=4
appVersion: "1.23.1"
