deployment:
  replicas: 1
  strategy: Recreate
  image:
    repository: ghcr.io/gethomepage/homepage
    tag: v0.8.9
    imagePullPolicy: IfNotPresent
  env:
  envFrom:
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 500m 
service:
  http:
    port: 3000
ingressRoute:
  host:
  authentik:
    outpost:
    port: 9000
config:
  bookmarks:
  services:
  widgets:
  kubernetes:
    mode: cluster
  docker:
  settings:
