deployment:
  replicas: 1
  strategy: Recreate
  image:
    repository: bbilly1/tubearchivist
    tag: v0.4.7
    imagePullPolicy: IfNotPresent
  env:
    TZ: UTC
  envFrom:
  resources:
    requests:
      memory: 512Mi
      cpu: 50m
    limits:
      memory: 1Gi
      cpu: 1000m
service:
  http:
    port: 8000
ingress:
  enabled: false
  className:
  annotations:
  host:
persistence:
  cache:
    enabled: false
    storageClassName: default
    storageSize: 5Gi
    accessMode: ReadWriteOnce
    volumeMode: Filesystem
  youtube:
    claimName:
redis:
  image:
    repository: redis/redis-stack-server
    tag: 7.2.0-v9
  architecture: standalone
  auth:
    enabled: false
  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
    # Enable Redis Json module
    loadmodule /opt/redis-stack/lib/rejson.so
elasticsearch:
  global:
    storageClass: default
  extraEnvVars:
    - name: "discovery.type"
      value: "single-node"
    - name: xpack.security.enabled
      value: "true"
  extraEnvVarsSecret:
  extraConfig:
    path:
      repo: /usr/share/elasticsearch/data/snapshot
  extraVolumes:
  extraVolumeMounts:
    - name: snapshot
      mountPath: /usr/share/elasticsearch/data/snapshot
  snapshotRepoPath: /usr/share/elasticsearch/data/snapshot
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    enabled: false
    replicaCount: 0
