{{- if .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: qbittorrent
  annotations:
    {{- toYaml .Values.server.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.server.ingress.className }}
  tls:
    - hosts:
      - {{ .Values.server.ingress.host }}
      secretName: qbittorrent-secret-tls
  rules:
    - host: {{ .Values.server.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: qbittorrent-webui
                port:
                  name: http
{{- end }}
