apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-webui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: qbittorrent
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}
