{{- if .Values.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "pocketIdClient.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pocketIdClient.secretName" . }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.storeName }}
  data:
    {{- if eq .Values.mode "oauth" }}
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: {{ include "pocketIdClient.secretPath" . }}
        property: clientId
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: {{ include "pocketIdClient.secretPath" . }}
        property: clientSecret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: {{ include "pocketIdClient.secretPath" . }}
        property: cookie
    - secretKey: OAUTH2_PROXY_OIDC_ISSUER_URL
      remoteRef:
        key: {{ .Values.issuerConfigPath | default "/cl01tl/pocket-id/config" }}
        property: issuer-url
    {{- else }}
    - secretKey: {{ include "pocketIdClient.clientIdKey" . }}
      remoteRef:
        key: {{ include "pocketIdClient.secretPath" . }}
        property: clientId
    - secretKey: {{ include "pocketIdClient.clientSecretKey" . }}
      remoteRef:
        key: {{ include "pocketIdClient.secretPath" . }}
        property: clientSecret
    {{- end }}
    {{- range .Values.externalSecret.extraData }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
{{- end }}
