---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: {{ include "pocketIdClient.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pocketIdClient.name" . }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: {{ include "pocketIdClient.displayName" . | quote }}
  launchUrl: {{ include "pocketIdClient.launchUrl" . }}
  description: {{ .Values.client.description | quote }}
  callbackUrls:
    {{- include "pocketIdClient.callbackUrls" . | nindent 4 }}
  pkceEnabled: {{ .Values.client.pkceEnabled }}
  skipConsent: {{ .Values.client.skipConsent }}
  allowedUserGroups:
    {{- range .Values.client.allowedUserGroups }}
    - name: {{ .name }}
      namespace: {{ .namespace }}
    {{- end }}
  clientID: {{ include "pocketIdClient.clientID" . }}
  clientSecretRef:
    name: {{ include "pocketIdClient.clientSecretRefName" . }}
    key: {{ include "pocketIdClient.clientSecretRefKey" . }}
  {{- if .Values.client.logo.enabled }}
  logo:
    logoUrl: {{ include "pocketIdClient.logoUrl" . }}
    {{- $darkLogo := include "pocketIdClient.darkLogoUrl" . }}
    {{- if $darkLogo }}
    darkLogoUrl: {{ $darkLogo }}
    {{- end }}
  {{- end }}
