apiVersion: v1
kind: Pod
metadata:
  name: matrix-hookshot-test-connection
  labels:
    app.kubernetes.io/name: matrix-hookshot-test-connection
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": test-success
spec:
  restartPolicy: Never
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['matrix-hookshot:{{ .Values.service.webhook.port }}']
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 256Mi
