{{- if not .Values.hookshot.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: matrix-hookshot-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: matrix-hookshot-config
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
data:
  config.yml: |
{{ toYaml .Values.hookshot.config | indent 4 }}
{{- end }}

---
{{- if not .Values.hookshot.existingRegistrationSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: matrix-hookshot-registration-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: matrix-hookshot-registration
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
data:
  registration.yml: |
{{ toYaml .Values.hookshot.registration | indent 4 }}
{{- end }}

---
{{- if not .Values.hookshot.existingPasskeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: matrix-hookshot-passkey-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: matrix-hookshot-passkey
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
data:
  {{ .Values.hookshot.config.passFile }}: |
{{ toYaml .Values.hookshot.passkey | indent 4 }}
{{- end }}
