{{- if .Values.secret.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "rclone.sourceSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secret.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "rclone.sourceSecretName" . }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secret.externalSecret.storeName | required "External Secret store name is required" }}
  data:
    - secretKey: {{ include "secret.envAccessKey" . }}
      remoteRef:
        key: {{ .Values.secret.externalSecret.source.credentials.path }}
        property: {{ .Values.secret.externalSecret.source.credentials.keyIdProperty }}
    - secretKey: {{ include "secret.envSecretKey" . }}
      remoteRef:
        key: {{ .Values.secret.externalSecret.source.credentials.path }}
        property: {{ .Values.secret.externalSecret.source.credentials.secretKeyProperty }}
    - secretKey: {{ include "secret.envRegion" . }}
      remoteRef:
        key: {{ .Values.secret.externalSecret.source.credentials.path }}
        property: {{ .Values.secret.externalSecret.source.credentials.regionProperty }}
    - secretKey: {{ include "secret.envSrcEndpoint" . }}
      remoteRef:
        key: {{ .Values.secret.externalSecret.source.config.path }}
        property: {{ .Values.secret.externalSecret.source.config.endpointProperty }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "rclone.destinationSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secret.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "rclone.destinationSecretName" . }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secret.externalSecret.storeName | required "External Secret store name is required" }}
  data:
    - secretKey: {{ include "secret.envAccessKey" . }}
      remoteRef:
        key: {{ .Values.secret.externalSecret.destination.credentials.path }}
        property: {{ .Values.secret.externalSecret.destination.credentials.keyIdProperty }}
    - secretKey: {{ include "secret.envSecretKey" . }}
      remoteRef:
        key: {{ .Values.secret.externalSecret.destination.credentials.path }}
        property: {{ .Values.secret.externalSecret.destination.credentials.keyIdProperty }}
    - secretKey: {{ include "secret.envRegion" . }}
      remoteRef:
        key: {{ .Values.secret.externalSecret.destination.credentials.path }}
        property: {{ .Values.secret.externalSecret.destination.credentials.keyIdProperty }}
    - secretKey: {{ include "secret.envDestEndpoint" . }}
      remoteRef:
        key: {{ .Values.secret.externalSecret.destination.config.path }}
        property: {{ .Values.secret.externalSecret.destination.config.endpointProperty }}
{{- end }}
