# -- Default pattern follows <pvcTarget>-backup
nameOverride: ""

# -- Add additional labels
additionalLabels: {}

# -- Default image
image:
  repository: rclone/rclone
  tag: 1.74.2@sha256:9ce0d49b611d3781233e25334e9e23d7af01e5546da7087f90d55f034ef13637
  pullPolicy: IfNotPresent

# -- CronJob configuration
cronJob:
  suspend: false
  timeZone: America/Chicago
  schedule: 0 0 * * *
  backoffLimit: 3
  parallelism: 1

# -- rclone configuration
rclone:
  providerType: Other

  # -- Source configuration
  source:
    providerType: Other
    bucketName: bucket
    forcePathStyle: true

  # -- Destination configuration
  destination:
    providerType: Other
    bucketName: bucket
    forcePathStyle: true

# -- Enable prune job
prune:
  enabled: false
  ageToPrune: 90d
  include: ""
  exclude: ""

# -- Secret configuration
secret:

  # -- External Secret configuration
  externalSecret:
    enabled: true
    storeName: openbao

    # -- Source configuration
    source:
      nameOverride: ""
      credentials:
        path: /credential
        keyIdProperty: ACCESS_KEY_ID
        secretKeyProperty: ACCESS_SECRET_KEY
        regionProperty: ACCESS_REGION
      config:
        path: /config
        endpointProperty: ENDPOINT_LOCAL

    # -- Destination configuration
    destination:
      nameOverride: ""
      credentials:
        path: /credential
        keyIdProperty: ACCESS_KEY_ID
        secretKeyProperty: ACCESS_SECRET_KEY
        regionProperty: ACCESS_REGION
      config:
        path: /config
        endpointProperty: ENDPOINT_REMOTE

    # -- Add additional labels
    additionalLabels: {}

  # -- Name of existing secret that contains the configuration
  existingSecretSource:
    name: rclone-source-secret

  existingSecretDestination:
    name: rclone-destination-secret

# -- Metrics
metrics:
  enabled: true

# -- Prometheus Rule
prometheusRule:
  enabled: true
