# -- Default pattern follows <pvcTarget>-backup
nameOverride: ""

# -- Add additional labels
additionalLabels: {}

# -- Default image
image:
  repository: rclone/rclone
  tag: 1.74.3@sha256:623378ad0ff3ebd5cebf77720843c0e02edfe46e2d5b5ac6bed54c6371780dfb
  pullPolicy: IfNotPresent

# -- CronJob configuration
cronJob:
  suspend: false
  timeZone: America/Chicago
  schedule: 0 0 * * *
  backoffLimit: 3
  parallelism: 1

# -- rclone configuration
rclone:
  providerType: Other

  # -- Source configuration
  source:
    providerType: Other
    bucketName: bucket
    forcePathStyle: true

  # -- Destination configuration
  destination:
    providerType: Other
    bucketName: bucket
    forcePathStyle: true

# -- Enable prune job
prune:
  enabled: false
  ageToPrune: 90d
  include: ""
  exclude: ""

# -- Notification configuration
ntfy:
  enabled: true

  # -- Provide an existing secret for the ntfy url
  existingSecret:
    name: ""
    key: ntfy-url

  # -- Generate a secret using ExternalSecret
  externalSecret:
    enabled: true
    storeName: openbao
    urlPath: /ntfy
    urlProperty: url
    topicPath: /ntfy
    topicProperty: topic

# -- Secret configuration
secret:
  # -- External Secret configuration
  externalSecret:
    enabled: true
    storeName: openbao

    # -- Source configuration
    source:
      nameOverride: ""
      credentials:
        path: /credential
        keyIdProperty: ACCESS_KEY_ID
        secretKeyProperty: ACCESS_SECRET_KEY
        regionProperty: ACCESS_REGION
      config:
        path: /config
        endpointProperty: ENDPOINT_LOCAL

    # -- Destination configuration
    destination:
      nameOverride: ""
      credentials:
        path: /credential
        keyIdProperty: ACCESS_KEY_ID
        secretKeyProperty: ACCESS_SECRET_KEY
        regionProperty: ACCESS_REGION
      config:
        path: /config
        endpointProperty: ENDPOINT_REMOTE

    # -- Add additional labels
    additionalLabels: {}

  # -- Name of existing secret that contains the configuration
  existingSecretSource:
    name: rclone-source-secret

  existingSecretDestination:
    name: rclone-destination-secret

# -- Metrics
metrics:
  enabled: true

# -- Prometheus Rule
prometheusRule:
  enabled: true
