# -- Default pattern follows <pvcTarget>-backup
nameOverride: ""

# -- Add additional labels
additionalLabels: {}

# -- Default image
image:
  repository: rclone/rclone
  tag: 1.73.5@sha256:1619a625f845e169c34b952cf40c483c0392965b821c5155cde8cbfd35254a96
  pullPolicy: IfNotPresent

# -- CronJob configuration
cronJob:
  suspend: false
  timeZone: America/Chicago
  schedule: 0 0 * * *
  backoffLimit: 3
  parallelism: 1

# -- rclone configuration
rclone:
  providerType: Other

  # -- Source configuration
  source:
    providerType: Other
    bucketName: bucket
    forcePathStyle: true

  # -- Destination configuration
  destination:
    providerType: Other
    bucketName: bucket
    forcePathStyle: true

# -- Enable prune job
prune:
  enabled: false
  ageToPrune: 90d

# -- Secret configuration
secret:

  # -- External Secret configuration
  externalSecret:
    enabled: true
    storeName: openbao

    # -- Source configuration
    source:
      nameOverride: ""
      credentials:
        path: /credential
        keyIdProperty: ACCESS_KEY_ID
        secretKeyProperty: ACCESS_SECRET_KEY
        regionProperty: ACCESS_REGION
      config:
        path: /config
        endpointProperty: ENDPOINT_LOCAL

    # -- Destination configuration
    destination:
      nameOverride: ""
      credentials:
        path: /credential
        keyIdProperty: ACCESS_KEY_ID
        secretKeyProperty: ACCESS_SECRET_KEY
        regionProperty: ACCESS_REGION
      config:
        path: /config
        endpointProperty: ENDPOINT_REMOTE

    # -- Add additional labels
    additionalLabels: {}

  # -- Name of existing secret that contains the configuration
  existingSecretSource:
    name: rclone-source-secret

  existingSecretDestination:
    name: rclone-destination-secret
