{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: calibre-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: calibre-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: calibre-server
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`{{ .Values.ingressRoute.http.host }}`)"
      middlewares:
        - name: "authentik-{{ .Release.Name }}"
          namespace: {{ .Release.Namespace }}
      priority: 10
      services:
        - kind: Service
          name: calibre-server
          port: {{ .Values.service.http.port }}
    - kind: Rule
      match: "Host(`{{ .Values.ingressRoute.http.host }}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
        - kind: Service
          name: {{ .Values.ingressRoute.authentik.outpost }}
          port: {{ .Values.ingressRoute.authentik.port }}
{{- end }}
