apiVersion: v1
kind: ServiceAccount
metadata:
  name: calibre-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: calibre-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: calibre-server
    app.kubernetes.io/managed-by: helm
