{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "taiga.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ template "taiga.fullname" . }}-secret-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: "{{ template "taiga.fullname" . }}-front"
                port:
                  name: taiga-front
            pathType: ImplementationSpecific
          - path: /api
            backend:
              service:
                name: "{{ template "taiga.fullname" . }}-back"
                port:
                  name: taiga-back
            pathType: ImplementationSpecific
          - path: /admin
            backend:
              service:
                name: "{{ template "taiga.fullname" . }}-back"
                port:
                  name: taiga-back
            pathType: ImplementationSpecific
          - path: /events
            backend:
              service:
                name: "{{ template "taiga.fullname" . }}-events"
                port:
                  name: taiga-events
            pathType: ImplementationSpecific
          - path: /media
            backend:
              service:
                name: "{{ template "taiga.fullname" . }}-protected"
                port:
                  name: taiga-protected
            pathType: ImplementationSpecific
{{- end }}
