name: lint-and-test

on:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-js
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up Chart Testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Run Chart Testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ gitea.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run Chart Testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --validate-maintainers=false --target-branch ${{ gitea.event.repository.default_branch }}

      - name: ntfy Failed
        uses: niniyas/ntfy-action@master
        if: failure()
        with:
          url: '${{ secrets.NTFY_URL }}'
          topic: '${{ secrets.NTFY_TOPIC }}'
          title: 'Test Failure - Helm Charts'
          priority: 3
          headers: '{"Authorization": "Bearer ${{ secrets.NTFY_CRED }}"}'
          tags: action,failed
          details: 'Tests have failed for Helm Charts'
          icon: 'https://cdn.jsdelivr.net/gh/selfhst/icons/png/gitea.png'
          actions: '[{"action": "view", "label": "Open Gitea", "url": "https://gitea.alexlebens.dev/alexlebens/helm-charts/actions?workflow=lint-test.yaml", "clear": true}]'
          image: true
