deployment:
  replicas: 1
  strategy: Recreate
  priorityClassName: system-cluster-critical
  image:
    repository: ghcr.io/alex1989hu/kubelet-serving-cert-approver
    tag: main
    imagePullPolicy: Always
  resources:
    limits:
      cpu: 250m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 16Mi
