apiVersion: v1
kind: Service
metadata:
  name: mautrix-discord
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mautrix-discord
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP | quote }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mautrix-discord
    app.kubernetes.io/instance: {{ .Release.Name }}
