{{- if .Values.referenceGrant.enabled }}
---
apiVersion: garage.rajsingh.info/v1beta2
kind: GarageReferenceGrant
metadata:
  name: {{ include "garageBucket.name" . }}-grant
  namespace: {{ .Values.garageCluster.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "garageBucket.name" . }}-grant
    {{- include "garageBucket.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  from:
    - group: garage.rajsingh.info
      kind: GarageKey
      name: {{ include "garageKey.name" . }}
      namespace: {{ .Release.Namespace }}
    - group: garage.rajsingh.info
      kind: GarageBucket
      name: {{ include "garageBucket.name" . }}
      namespace: {{ .Release.Namespace }}
  to:
    - group: garage.rajsingh.info
      kind: GarageCluster
      name: {{ .Values.garageCluster.name }}
{{- end }}
