{{- if .Values.cors.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "garageBucket.name" . }}-cors-apply
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "garageBucket.name" . }}-cors-apply
    {{- include "garageBucket.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: {{ include "garageBucket.name" . }}-cors-apply
      labels:
        app.kubernetes.io/name: {{ include "garageBucket.name" . }}-cors-apply
    spec:
      restartPolicy: OnFailure
      containers:
      - name: aws-cli
        image: "{{ .Values.cors.image.repository }}:{{ .Values.cors.image.tag }}"
        command:
        - /bin/sh
        - -c
        - |
          echo ">> Applying CORS configuration to {{ include "garageBucket.name" . }} bucket..."
          aws s3api put-bucket-cors \
            --bucket {{ include "garageBucket.name" . }} \
            --cors-configuration file:///etc/config/cors.json \
            --endpoint-url http://{{ .Values.garageCluster.name }}.{{ .Values.garageCluster.namespace }}.svc.cluster.local:3900 \
            --region garage
          echo ">> Done!"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "garageKey.name" . }}
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "garageKey.name" . }}
              key: secret-access-key
        volumeMounts:
        - name: config
          mountPath: /etc/config
      volumes:
      - name: config
        configMap:
          name: {{ include "garageBucket.name" . }}-cors
{{- end }}
