apiVersion: v2
name: outline
version: 0.1.2
description: Chart for Outline wiki
keywords:
  - wiki
  - documentation
sources:
  - https://github.com/outline/outline
  - https://github.com/bitnami/charts/tree/main/bitnami/redis
maintainers:
  - name: alexlebens
icon: https://avatars.githubusercontent.com/u/1765001?s=48&v=4
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.19.4
appVersion: v0.75.2
