deployment:
  replicas: 1
  strategy: Recreate
  image:
    repository: outlinewiki/outline
    tag: "0.75.2"
    imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 1Gi
      cpu: 500m
service:
  web:
    port: 3000
ingress:
  enabled: true
  className:
  annotations:
  host:
persistence:
  type: s3
  s3:
    credentialsSecret:
    endpointConfigMap:
      enabled: false
      name:
    region:
    bucketName:
    host:
    urlProtocol: http
    uploadMaxSize: "26214400"
    forcePathStyle: false
    acl: private
  local:
    storageClassName: default
    storageSize: 50Gi
    localRootDir: /var/lib/outline/data
    uploadMaxSize: 26214400
outline:
  nodeEnv: production
  url:
  secretKey:
    existingSecretName: outline-key-secret
    existingSecretKey: secret-key
  utilsSecret:
    existingSecretName: outline-key-secret
    existingSecretKey: utils-key
  database:
    passwordSecret:
      existingSecretName:
      existingSecretKey:
    usernameSecret:
      existingSecretName:
      existingSecretKey:
    databaseName:
      existingSecretName:
      existingSecretKey:
    databaseHost:
      existingSecretName:
      existingSecretKey:
    databasePort:
      existingSecretName:
      existingSecretKey:      
    connectionPoolMin: ""
    connectionPoolMax: "20"
    sslMode: disable
  optional:
    forceHttps: false
    enableUpdates: false
    webConcurrency: 1
    maximumImportSize: 5120000
    logLevel: info
    defaultLanguage: en_US
    rateLimiter:
      enabled: false
      requests: 1000
      durationWindow: 60
    developmentUnsafeInlineCsp: false
  auth:
    oidc:
      enabled: true
      clientId:
        existingSecretName: outline-auth-secret
        existingSecretKey: oidc-client-id
      clientSecret:
        existingSecretName: outline-auth-secret
        existingSecretKey: oidc-client-secret
      authUri:
      tokenUri:
      userinfoUri:
      usernameClaim:
      displayName:
      scopes: openid profile email
redis:
  image:
    registry: docker.io
    repository: valkey/valkey
    tag: 7.2.4-rc1
  architecture: standalone
  auth:
    enabled: false
