global:
  serviceAccount:
    create: true
  env: []
  persistence:
    media:
      claimName:
      mountPath:
server:
  replicas: 1
  strategy: Recreate
  image:
    repository: linuxserver/qbittorrent
    tag: "version-4.6.3-r0"
    pullPolicy: IfNotPresent
  env:
    - name: TZ
      value: UTC
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: UMASK_SET
      value: "002"
  resources:
    requests:
      cpu: 100m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  service:
    http:
      port: 8080
  ingress:
    enabled: false
    className:
    annotations:
    host:
  persistence:
    config:
      storageClassName:
      storageSize:
gluetun:
  enabled: false
  image:
    repository: ghcr.io/qdm12/gluetun
    tag: v3.38.0
    pullPolicy: IfNotPresent
  securityContext:
    privileged: True
    capabilities:
      add:
        - NET_ADMIN
  env: []
  existingSecretName:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  service:
    health:
      port: 9999
metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 15s
    scrapeTimeout: 5s
  exporter:
    image:
      repository: esanchezm/prometheus-qbittorrent-exporter
      tag: v1.5.1
      imagePullPolicy: IfNotPresent
    env:
      - name: QBITTORRENT_USER
        value: admin
      - name: QBITTORRENT_PASS
        value: ""
      - name: EXPORTER_LOG_LEVEL
        value: INFO
