kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cops-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.storageSize }}
  storageClassName: {{ .Values.persistence.config.storageClassName }}
  volumeMode: {{ .Values.persistence.config.volumeMode }}
