{{- if .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tdarr-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: tdarr-server
  annotations:
    {{- toYaml .Values.server.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.server.ingress.className }}
  tls:
    - hosts:
      - {{ .Values.server.ingress.host }}
      secretName: tdarr-server-secret-tls
  rules:
    - host: {{ .Values.server.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: tdarr-server-web
                port:
                  name: web
{{- end }}
