apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.persistence.config.storageSize }}
  storageClassName: {{ .Values.server.persistence.config.storageClassName }}
  volumeMode: {{ .Values.server.persistence.config.volumeMode }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.persistence.server.storageSize }}
  storageClassName: {{ .Values.server.persistence.server.storageClassName }}
  volumeMode: {{ .Values.server.persistence.server.volumeMode }}
