apiVersion: v1
kind: Service
metadata:
  name: tdarr-server-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: tdarr-server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: tdarr-server-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: tdarr-server
spec:
  ports:
    - port: {{ .Values.server.service.web.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/instance: {{ .Release.Name }}
