apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "cluster.name" . }}-cluster
  namespace: {{ .Release.Namespace }}
  {{- with .Values.cluster.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
  {{- with .Values.cluster.additionalLabels }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  instances: {{ .Values.cluster.instances }}
  imageName: "{{ .Values.cluster.image.repository }}:{{ .Values.cluster.image.tag }}"
  imagePullPolicy: {{ .Values.cluster.image.pullPolicy }}
  postgresUID: {{ .Values.cluster.postgresUID }}
  postgresGID: {{ .Values.cluster.postgresGID }}
  walStorage:
    size: {{ .Values.cluster.walStorage.size }}
    storageClass: {{ .Values.cluster.walStorage.storageClass }}
  storage:
    size: {{ .Values.cluster.storage.size }}
    storageClass: {{ .Values.cluster.storage.storageClass }}
  {{- with .Values.cluster.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{ end }}
  {{- with .Values.cluster.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.cluster.priorityClassName }}
  priorityClassName: {{ .Values.cluster.priorityClassName }}
  {{- end }}
  primaryUpdateMethod: {{ .Values.cluster.primaryUpdateMethod }}
  primaryUpdateStrategy: {{ .Values.cluster.primaryUpdateStrategy }}
  logLevel: {{ .Values.cluster.logLevel }}
  postgresql:
    {{- if eq .Values.type "timescaledb" }}
    shared_preload_libraries:
      - timescaledb
    {{- end }}
    {{- if eq .Values.type "tensorchord" }}
    shared_preload_libraries:
      - vectors.so
    enableAlterSystem: true
    {{- end }}
    {{- with .Values.cluster.postgresql.shared_preload_libraries }}
    shared_preload_libraries:
      {{- toYaml . | nindent 6 }}
    {{ end }}
    {{- with .Values.cluster.postgresql.parameters }}
    parameters:
      {{- toYaml . | nindent 6 }}
    {{ end }}
  monitoring:
    enablePodMonitor: {{ and .Values.cluster.monitoring.enabled .Values.cluster.monitoring.podMonitor.enabled }}

  {{ include "cluster.bootstrap" . | nindent 2 }}

  {{ include "cluster.backup" . | nindent 2 }}
