{{- if (eq .Values.backup.method "objectStore") }}
{{- $context := . }}
{{- with .Values.backup.objectStore }}
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ include "cluster.backupName" $context }}
  namespace: {{ include "cluster.namespace" $context }}
  labels:
    app.kubernetes.io/name: {{ include "cluster.backupName" $context }}
    {{- include "cluster.labels" $context | nindent 4 }}
spec:
  retentionPolicy: {{ .retentionPolicy | default "7d" }}
  # Required when not using AWS S3
  # https://github.com/cloudnative-pg/cloudnative-pg/issues/8599
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
  configuration:
    destinationPath: {{ include "cluster.backupDestinationPath" $context }}
    endpointURL: {{ .endpointURL }}
    {{- if .endpointCA }}
    {{- if or .endpointCA.name .endpointCA.createExternalSecret }}
    endpointCA:
      name: {{ include "cluster.backupCaSecretName" $context }}
      key: {{ .endpointCA.key | default "ca.crt" }}
    {{- end }}
    {{- end }}
    {{- with .wal }}
    wal:
      compression: {{ .compression | default "snappy" }}
      {{- if .encryption }}
      encryption: {{ .encryption }}
      {{- end }}
      maxParallel: {{ .maxParallel | default "2" }}
    {{- end }}
    {{- with .data }}
    data:
      compression: {{ .compression | default "snappy" }}
      {{- if .encryption }}
      encryption: {{ .encryption }}
      {{- end }}
      jobs: {{ .jobs | default 2 }}
    {{- end }}
    s3Credentials:
      accessKeyId:
        name: {{ include "cluster.backupSecretName" $context }}
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: {{ include "cluster.backupSecretName" $context }}
        key: ACCESS_SECRET_KEY
      region:
        name: {{ include "cluster.backupSecretName" $context }}
        key: ACCESS_REGION
{{- end }}
{{- end }}

{{- if eq .Values.recovery.method "objectStore" }}
{{- $context := . }}
{{- with .Values.recovery.objectStore }}
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ include "cluster.recoveryName" $context }}
  namespace: {{ include "cluster.namespace" $context }}
  labels:
    app.kubernetes.io/name: {{ include "cluster.recoveryName" $context }}
    {{- include "cluster.labels" $context | nindent 4 }}
spec:
  configuration:
    destinationPath: {{ include "cluster.recoveryDestinationPath" $context }}
    endpointURL: {{ .endpointURL }}
    {{- if .endpointCA }}
    {{- if or .endpointCA.name .endpointCA.createExternalSecret }}
    endpointCA:
      name: {{ include "cluster.recoveryCaSecretName" $context }}
      key: {{ .endpointCA.key | default "ca.crt" }}
    {{- end }}
    {{- end }}
    {{- with .wal }}
    wal:
      compression: {{ .compression | default "snappy" }}
      {{- if .encryption }}
      encryption: {{ .encryption }}
      {{- end }}
      maxParallel: {{ .maxParallel | default "2" }}
    {{- end }}
    {{- with .data }}
    data:
      compression: {{ .compression | default "snappy" }}
      {{- if .encryption }}
      encryption: {{ .encryption }}
      {{- end }}
      jobs: {{ .jobs | default 2 }}
    {{- end }}
    s3Credentials:
      accessKeyId:
        name: {{ include "cluster.recoverySecretName" $context }}
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: {{ include "cluster.recoverySecretName" $context }}
        key: ACCESS_SECRET_KEY
      region:
        name: {{ include "cluster.recoverySecretName" $context }}
        key: ACCESS_REGION
{{- end }}
{{- end }}
