{{ $context := . -}}
{{ range .Values.backup.scheduledBackups -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: "{{ include "cluster.name" $context }}-{{ .name }}-scheduled-backup"
  namespace: {{ include "cluster.namespace" $context }}
  labels:
    {{- include "cluster.labels" $context | nindent 4 }}
spec:
  immediate: {{ .immediate | default false }}
  suspend: {{ .suspend | default false }}
  schedule: {{ .schedule | quote | required "Schedule is required" }}
  backupOwnerReference: {{ .backupOwnerReference | default "self" }}
  cluster:
    name: {{ include "cluster.name" $context }}-cluster
  method: plugin
  pluginConfiguration:
    name: {{ .plugin | default "barman-cloud.cloudnative-pg.io" }}
    parameters:
      barmanObjectName: "{{ include "cluster.name" $context }}-{{ .backupName }}-backup"
{{ end -}}
