{{ if .Values.backup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "cluster.name" . }}-scheduled-backup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
  {{- with .Values.cluster.additionalLabels }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  immediate: true
  schedule: {{ .Values.backup.schedule }}
  backupOwnerReference: self
  cluster:
    name: {{ include "cluster.name" . }}-cluster
{{ end }}
