{{ if .Values.backup.enabled }}
{{ $context := . -}}
{{ range .Values.backup.scheduledBackups -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: "{{ include "cluster.name" $context }}-{{ .name }}-scheduled-backup"
  namespace: {{ include "cluster.namespace" $context }}
  labels:
    {{- include "cluster.labels" $context | nindent 4 }}
spec:
  immediate: true
  suspend: {{ .suspend }}
  schedule: {{ .schedule | quote }}
  backupOwnerReference: {{ .backupOwnerReference }}
  cluster:
    name: {{ include "cluster.name" $context }}-cluster
  method: plugin
  pluginConfiguration:
    name: {{ .plugin }}
    parameters:
      barmanObjectName: "{{ include "cluster.name" $context }}-{{ .backupName }}-backup"
{{ end -}}
{{ end }}
