{{ if .Values.backup.enabled }}
{{ $context := . -}}
{{ range .Values.backup.scheduledBackups -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: "{{ include "cluster.name" . }}-{{ $context.name }}-scheduled-backup"
  namespace: {{ include "cluster.namespace" . }}
  labels:
    {{- include "cluster.labels" $context | nindent 4 }}
spec:
  immediate: true
  suspend: {{ $context.suspend }}
  schedule: {{ $context.schedule | quote }}
  backupOwnerReference: {{ $context.backupOwnerReference }}
  cluster:
    name: {{ include "cluster.name" . }}-cluster
  method: plugin
  pluginConfiguration:
    name: {{ $context.plugin }}
    parameters:
      barmanObjectName: "{{ include "cluster.name" . }}-{{ $context.backupName }}-backup"
{{ end -}}
{{ end }}
