cluster:
  name: cl01tl
  image:
    repository: ghcr.io/cloudnative-pg/postgresql
    tag: 16.2
  instances: 2
  parameters:
    shared_buffers: 128MB
    max_slot_wal_keep_size: 2000MB
    hot_standby_feedback: "on"
  compression: snappy
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 2Gi
      cpu: 1500m
      hugepages-2Mi: 512Mi
  storage:
    data:
      storageClass:
      size: 10Gi
    wal:
      storageClass:
      size: 2Gi
bootstrap:
  recoveryEnabled: false
  recoveryIndex: 1
  endpointURL:
  bucket:
  initdbEnabled: false
  initdb:
    database: app
    owner: app
backup:
  backupEnabled: true
  schedule: "0 0 0 * * *"
  retentionPolicy: 14d
  backupIndex: 1
  endpointURL:
  bucket:
