bucketName: "test-bucket"
backups:
  primary:
    enabled: true
    destination:
      bucketName: "test-bucket-backup"
  secondary:
    enabled: true
    destination:
      bucketName: "test-bucket-backup-secondary"
