global:
  serviceAccount:
    create: true
  env:
    - name: TZ
      value: UTC
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: UMASK_SET
      value: "002"
    - name: ffmpegVersion
      value: "6"
  persistence:
    media:
      claimName:
      mountPath:
server:
  replicas: 1
  strategy: Recreate
  image:
    repository: ghcr.io/haveagitgat/tdarr
    tag: "2.17.01"
    pullPolicy: IfNotPresent
  env: []
  envFrom: []
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  service:
    api:
      port: 8266
    web:
      port: 8265
  ingress:
    enabled: false
    className:
    annotations:
    host:
  persistence:
    config:
      storageClassName: default
      storageSize: 5Gi
      volumeMode: Filesystem
    server:
      storageClassName: default
      storageSize: 5Gi
      volumeMode: Filesystem
    cache:
      size: 100Mi
node:
  replicas: 3
  strategy: Recreate  
  image:
    repository: ghcr.io/haveagitgat/tdarr_node
    tag: "2.17.01"
    pullPolicy: IfNotPresent
  env: []
  envFrom: []
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  persistence:
    cache:
      size: 5Gi
tdarr-exporter:
  metrics:
    serviceMonitor:
      enabled: false
      interval: 30s
      scrapeTimeout: 30s
  settings:
    config:
      url:
      verify_ssl: false
      log_level: "info"
