# -- Name override of release
name: ""

# -- Number of replicas for high availability (Cloudflare recommends at least 2)
replicas: 2

# -- Protocol - Available values are auto, http2, and quic.
protocol: auto

# -- Probes configuration
probes:
  liveness:
    enabled: true
  readiness:
    enabled: true

# -- Metrics
metrics:
  enabled: true

# -- Secret configuration
secret:

  # -- External Secret configuration
  externalSecret:
    enabled: true
    nameOverride: ""

    # -- Cluster store config
    store:
      name: openbao
      path: /cloudflare/tunnels
      property: token

    # -- Add additional labels
    additionalLabels: {}

  # -- Name of existing secret that contains Cloudflare token
  existingSecret:
    name: cloudflared-secret
    key: cf-tunnel-token

# -- Default image
image:
  repository: cloudflare/cloudflared
  tag: 2026.6.1@sha256:6d91c121b803126f7a5344005d17a9324788fc09d305b6e2560ec6040a7ae283
  pullPolicy: IfNotPresent

# -- Default resources
resources:
  requests:
    cpu: 1m
    memory: 20Mi
