# -- Name override of release
name: ""

# -- Protocol - Available values are auto, http2, and quic.
protocol: auto

# -- Metrics
metrics:
  enabled: true

# -- Secret configuration
secret:

  # -- External Secret configuration
  externalSecret:
    enabled: true
    nameOverride: ""

    # -- Cluster store config
    store:
      name: openbao
      path: /cloudflare/tunnels
      property: token

    # -- Add additional labels
    additionalLabels: {}

  # -- Name of existing secret that contains Cloudflare token
  existingSecret:
    name: cloudflared-secret
    key: cf-tunnel-token

# -- Default image
image:
  repository: cloudflare/cloudflared
  tag: 2026.5.1@sha256:a5b5e6fd9a372f054b9a843c219bfbcdceb54691605312a8b1ee72978bdf1aa1
  pullPolicy: IfNotPresent

# -- Default resources
resources:
  requests:
    cpu: 1m
    memory: 20Mi
