# -- Name override of release
name: ""

# -- Protocol - Available values are auto, http2, and quic.
protocol: auto

# -- Metrics
metrics:
  enabled: true

# -- Secret configuration
secret:

  # -- External Secret configuration
  externalSecret:
    enabled: true
    nameOverride: ""

    # -- Cluster store config
    store:
      name: openbao
      path: /cloudflare/tunnels
      property: token

    # -- Add additional labels
    additionalLabels: {}

  # -- Name of existing secret that contains Cloudflare token
  existingSecret:
    name: cloudflared-secret
    key: cf-tunnel-token

# -- Default image
image:
  repository: cloudflare/cloudflared
  tag: 2026.6.0@sha256:ba461b8aa9c042156dbd39c38657fe7431bafa063220eab8d5330a523863da9f
  pullPolicy: IfNotPresent

# -- Default resources
resources:
  requests:
    cpu: 1m
    memory: 20Mi
