{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: home-assistant
    app.kubernetes.io/managed-by: helm
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`{{ .Values.ingressRoute.host }}`)"
      middlewares:
        - name: authentik
          namespace: {{ .Release.Namespace }}
      priority: 10
      services:
        - kind: Service
          name: home-assistant
          port: {{ .Values.service.http.port }}
    - kind: Rule
      match: "Host(`{{ .Values.ingressRoute.host }}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
        - kind: Service
          name: {{ .Values.ingressRoute.authentik.outpost }}
          port: {{ .Values.ingressRoute.authentik.port }}
{{- end }}

---
{{- if and .Values.codeserver.ingressRoute.enabled .Values.codeserver.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-codeserver
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: home-assistant
    app.kubernetes.io/managed-by: helm
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`{{ .Values.codeserver.ingressRoute.host }}`)"
      priority: 10
      services:
        - kind: Service
          name: home-assistant-codeserver
          port: {{ .Values.codeserver.service.http.port }}
{{- end }}          
