apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: {{ .Release.Namespace }}  
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.http.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: {{ .Release.Name }}

---
{{- if .Values.codeserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-codeserver
  namespace: {{ .Release.Namespace }}  
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.codeserver.service.http.port }}
    targetPort: codeserver-http
    protocol: TCP
    name: codeserver-http
  selector:
    app.kubernetes.io/name: codeserver
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
