apiVersion: batch/v1
kind: CronJob
metadata:
  name: tubearchivist-to-jellyfin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tubearchivist-to-jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: job
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  schedule: {{ .Values.job.schedule }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: tubearchivist-to-jellyfin
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["python"]
              args: ["main.py"]
              {{- with .Values.envFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: tubearchivist-youtube
                  mountPath: /data
          volumes:
            - name: tubearchivist-youtube
              persistentVolumeClaim:
                claimName: {{ .Values.persistence.youtube.claimName }}
