apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: "{{ .Release.Name }}-sa-token"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: homepage
    app.kubernetes.io/managed-by: helm
  annotations:
    kubernetes.io/service-account.name: homepage
