job:
  schedule: "0 * * * *"
image:
  repository: rmcrackan/libation
  tag: "11.3.13"
  pullPolicy: IfNotPresent
persistence:
  config:
    storageClassName: default
    storageSize: 1Gi
    volumeMode: Filesystem
  books:
    claimName:
