{{- range $tier := tuple "a" "b" "c" "d" }}
{{- $tierConfig := index $.Values $tier }}
{{- if and $tierConfig $tierConfig.enabled }}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: {{ include "volsync.name" $ }}-source-{{ $tier }}
  namespace: {{ include "volsync.namespace" $ }}
  labels:
    {{- include "volsync.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ include "volsync.name" $ }}-source-{{ $tier }}
    {{- with $.Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  sourcePVC: {{ $.Values.pvcTarget | required "PVC target is required" }}
  trigger:
    schedule: {{ $tierConfig.schedule }}
    {{- with (coalesce $tierConfig.manual $.Values.manual) }}
    manual: {{ . | quote }}
    {{- end }}
  {{- if or $tierConfig.paused $.Values.paused }}
  paused: true
  {{- end }}
  restic:
    pruneIntervalDays: {{ $tierConfig.restic.pruneIntervalDays }}
    repository: {{ include "volsync.repoName" (dict "root" $ "tier" $tier) }}
    retain:
    {{- with $tierConfig.restic.retain }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (coalesce $tierConfig.restic.unlock $tierConfig.unlock $.Values.unlock) }}
    unlock: {{ . | quote }}
    {{- end }}
    {{- if or $tierConfig.moverSecurityContext $.Values.moverSecurityContext }}
    moverSecurityContext:
    {{- with (coalesce $tierConfig.moverSecurityContext $.Values.moverSecurityContext) }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    copyMethod: {{ $tierConfig.restic.copyMethod }}
    storageClassName: {{ $tierConfig.restic.storageClassName }}
    volumeSnapshotClassName: {{ $tierConfig.restic.volumeSnapshotClassName }}
    cacheCapacity: {{ $tierConfig.restic.cacheCapacity }}
    {{- with $tierConfig.restic.cacheStorageClassName }}
    cacheStorageClassName: {{ . }}
    {{- end }}
    {{- with $tierConfig.restic.cacheAccessModes }}
    cacheAccessModes:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
