apiVersion: v1
kind: Service
metadata:
  name: outline-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: outline-web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: outline
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: outline-web
    app.kubernetes.io/instance: {{ .Release.Name }}
