apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: {{ include "cluster.name" . }}-cluster
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
    {{- include "cluster.selectorLabels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  instances: {{ required "serverInstances is required" .Values.cluster.serverInstances }}
  baseServerId: {{ required "baseServerId is required" .Values.cluster.baseServerId }}  
  serviceAccountName: {{ include "mysql.serviceAccountName" . }}  
  imagePullPolicy : {{ .Values.cluster.image.pullPolicy }}
  version: {{ .Values.cluster.image.version }}
  tlsUseSelfSigned: true
  secretName: {{ .Values.cluster.exisitingCredentialsSecret }}
  podSpec:
    {{- if .Values.cluster.podSpec }}
    {{ toYaml .Values.cluster.podSpec | nindent 4 }}
    {{- end }}
  podAnnotations:
    {{- if .Values.cluster.podAnnotations }}
    {{ toYaml .Values.cluster.podAnnotations | nindent 4 }}
    {{- end }}
  podLabels:
    {{- if .Values.cluster.podLabels }}
    {{ toYaml .Values.cluster.podLabels | nindent 4 }}
    {{- end }}
  router:
    instances: {{ required "router.instances is required" .Values.cluster.router.instances }}
    podSpec:
      {{- if .Values.cluster.router.podSpec }}
      {{- toYaml .Values.cluster.router.podSpec | nindent 6 }}
      {{- end }}
    podAnnotations:
      {{- if .Values.cluster.router.podAnnotations }}
      {{- toYaml .Values.cluster.router.podAnnotations | nindent 6 }}
      {{- end }}
    podLabels:
      {{- if .Values.cluster.router.podLabels }}
      {{- toYaml .Values.cluster.router.podLabels | nindent 6 }}
      {{- end }}
    tlsSecretName: {{ include "cluster.name" . }}-router-tls
  logs:
    {{- with .Values.cluster.logs }}
    {{ toYaml . | nindent 4 }}
    {{- end }}      
  mycnf: |
{{ .Values.cluster.serverConfig.mycnf | indent 4 }}
  {{- if .Values.cluster.datadirVolumeClaimTemplate }}
  {{- with .Values.cluster.datadirVolumeClaimTemplate }}
  datadirVolumeClaimTemplate:
    {{- if .storageClassName }}
    storageClassName: {{ .storageClassName | quote }}
    {{- end}}
    {{- if .accessModes }}
    accessModes: [ "{{ .accessModes }}" ]
    {{- end }}
    {{- if .size }}
    resources:
      requests:
        storage: "{{ .size }}"
    {{- end }}
  {{- end }}
  {{- end }}

  {{ include "cluster.init" . | nindent 2 }}
  {{ include "cluster.backup" . | nindent 2 }}
